version: '3.8'

services:
  main-db:
   image: mysql
   restart: always
   environment:
      MYSQL_DATABASE: 'MYSQL'
      MYSQL_ROOT_PASSWORD: '12345'
   ports:
    - '3306:3306'
   expose:
    - '3306'
